[project]
name = "comfyui-mnemic-nodes"
description = "LoRA Tag Loader now also supports timing control for video LoRA loading. Batch processing is now (hopefully), actually processing the batch at the same time."
version = "3.1.6"
license = { file = "LICENSE" }
dependencies = ["configparser", "groq", "transformers", "torch", "tiktoken", "imageio", "tqdm", "piexif", "requests", "colorama", "opencv-python", "python-dotenv"]

[project.urls]
Repository = "https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "mnemic"
DisplayName = "ComfyUI-mnemic-nodes"
Icon = ""
