[project]
name = "comfyui-mnemic-nodes"
description = "Made the temp image loader not complain about missing images, and accessing the input folder"
version = "3.0.2"
license = { file = "LICENSE" }
dependencies = ["configparser", "groq", "transformers", "torch", "tiktoken", "imageio", "tqdm", "piexif", "requests", "colorama", "opencv-python"]

[project.urls]
Repository = "https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "mnemic"
DisplayName = "ComfyUI-mnemic-nodes"
Icon = ""
