import { app } from "../../../scripts/app.js";

app.registerExtension({
  name: "MNeMiC.Settings",
  settings: [
    {
      id: "MNeMiC.LoRALoading.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "LoRA Loading", "Console Logging"],
      tooltip: "Log LoRA Tag Loader matching and loading details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.LoRALoading.FuzzySearch",
      name: "Fuzzy search",
      category: ["⚡MNeMiC Nodes", "LoRA Loading", "Fuzzy Search"],
      tooltip: "Allow LoRA Tag Loader to fall back to fuzzy (partial/reordered word) filename matching when no exact match is found. Disabled by default so only exact, base, numbered and prefix/contains matches are used.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.WildcardProcessing.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Console Logging"],
      tooltip: "Log Wildcard Processor, Wildcard Processor Advanced and Batch Wildcard Sampler matching and processing details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.WildcardProcessing.FuzzySearch",
      name: "Fuzzy search",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Fuzzy Search"],
      tooltip: "Allow wildcard matching to fall back to fuzzy (partial/reordered word) filename matching when no exact match is found. Disabled by default so only exact, base, numbered and prefix/contains matches are used.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.LoRALoading.MaxLoggedCandidates",
      name: "Max logged candidates",
      category: ["⚡MNeMiC Nodes", "LoRA Loading", "Max Logged Candidates"],
      tooltip: "How many candidate LoRA files to list in the console log when Console Logging is on. LoRA folders can hold hundreds of matches, so the log only shows the most relevant ones.",
      type: "number",
      attrs: { min: 1, max: 100, step: 1 },
      defaultValue: 15,
    },
    {
      id: "MNeMiC.WildcardProcessing.MaxLoggedCandidates",
      name: "Max logged candidates",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Max Logged Candidates"],
      tooltip: "How many candidate wildcard files to list in the console log when Console Logging is on. Wildcard folders can hold hundreds of matches, so the log only shows the most relevant ones.",
      type: "number",
      attrs: { min: 1, max: 100, step: 1 },
      defaultValue: 15,
    },
    {
      id: "MNeMiC.WildcardProcessing.MaxNestedPasses",
      name: "Max nested passes",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Max Nested Passes"],
      tooltip: "Maximum number of passes when resolving wildcards nested inside other wildcards. Increase if you have deeply nested wildcard chains that aren't fully resolving.",
      type: "number",
      attrs: { min: 1, max: 50, step: 1 },
      defaultValue: 10,
    },
    {
      id: "MNeMiC.GroqLLM.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq LLM API", "Console Logging"],
      tooltip: "Log Groq LLM API request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqLLM.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq LLM API", "Request Timeout"],
      tooltip: "How long to wait for the Groq LLM API to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.GroqCompletion.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq Completion API", "Console Logging"],
      tooltip: "Log Groq Completion API request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqCompletion.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq Completion API", "Request Timeout"],
      tooltip: "How long to wait for the Groq Completion API to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.GroqTranscribe.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Transcribe", "Console Logging"],
      tooltip: "Log Groq ALM API - Transcribe request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqTranscribe.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Transcribe", "Request Timeout"],
      tooltip: "How long to wait for the Groq ALM API - Transcribe to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.GroqTranslate.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Translate", "Console Logging"],
      tooltip: "Log Groq ALM API - Translate request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqTranslate.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Translate", "Request Timeout"],
      tooltip: "How long to wait for the Groq ALM API - Translate to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.PromptPropertyExtractor.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Prompt Property Extractor", "Console Logging"],
      tooltip: "Log Prompt Property Extractor parsing/matching details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.LoadRandomCheckpoint.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Load Random Checkpoint", "Console Logging"],
      tooltip: "Log Load Random Checkpoint pool/matching details to the console.",
      type: "boolean",
      defaultValue: false,
    },
  ],
});
