import { app } from "../../../scripts/app.js";

app.registerExtension({
  name: "MNeMiC.Settings",
  settings: [
    {
      id: "MNeMiC.LoRALoading.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "LoRA Loading", "Console Logging"],
      tooltip: "Log LoRA Tag Loader matching and loading details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.LoRALoading.FuzzySearch",
      name: "Fuzzy search",
      category: ["⚡MNeMiC Nodes", "LoRA Loading", "Fuzzy Search"],
      tooltip: "Allow LoRA Tag Loader to fall back to fuzzy (partial/reordered word) filename matching when no exact match is found. Disabled by default so only exact, base, numbered and prefix/contains matches are used.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.WildcardProcessing.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Console Logging"],
      tooltip: "Log Wildcard Processor, Wildcard Processor Advanced and Batch Wildcard Sampler matching and processing details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.WildcardProcessing.FuzzySearch",
      name: "Fuzzy search",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Fuzzy Search"],
      tooltip: "Allow wildcard matching to fall back to fuzzy (partial/reordered word) filename matching when no exact match is found. Disabled by default so only exact, base, numbered and prefix/contains matches are used.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.LoRALoading.MaxLoggedCandidates",
      name: "Max logged candidates",
      category: ["⚡MNeMiC Nodes", "LoRA Loading", "Max Logged Candidates"],
      tooltip: "How many candidate LoRA files to list in the console log when Console Logging is on. LoRA folders can hold hundreds of matches, so the log only shows the most relevant ones.",
      type: "number",
      attrs: { min: 1, max: 100, step: 1 },
      defaultValue: 15,
    },
    {
      id: "MNeMiC.WildcardProcessing.MaxLoggedCandidates",
      name: "Max logged candidates",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Max Logged Candidates"],
      tooltip: "How many candidate wildcard files to list in the console log when Console Logging is on. Wildcard folders can hold hundreds of matches, so the log only shows the most relevant ones.",
      type: "number",
      attrs: { min: 1, max: 100, step: 1 },
      defaultValue: 15,
    },
    {
      id: "MNeMiC.WildcardProcessing.MaxNestedPasses",
      name: "Max nested passes",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Max Nested Passes"],
      tooltip: "Maximum number of passes when resolving wildcards nested inside other wildcards. Increase if you have deeply nested wildcard chains that aren't fully resolving.",
      type: "number",
      attrs: { min: 1, max: 50, step: 1 },
      defaultValue: 10,
    },
    {
      id: "MNeMiC.GroqLLM.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq LLM API", "Console Logging"],
      tooltip: "Log Groq LLM API request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqLLM.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq LLM API", "Request Timeout"],
      tooltip: "How long to wait for the Groq LLM API to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.LLM.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Console Logging"],
      tooltip: "Log LLM Request requests and replies to the console. API keys are never logged.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.LLM.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Request Timeout"],
      tooltip: "How long to wait for the endpoint before giving up. Local models can take a while to load on first use.",
      type: "number",
      attrs: { min: 5, max: 3600, step: 5 },
      defaultValue: 300,
    },
    {
      id: "MNeMiC.LLM.PreviewHeight",
      name: "Reply preview height (px)",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Preview Height"],
      tooltip: "Default height of the reply preview area on a new LLM Request node. Drag the preview's bottom edge to resize an individual node; that height is then remembered on the node instead.",
      type: "number",
      attrs: { min: 40, max: 2000, step: 10 },
      defaultValue: 240,
    },
    {
      id: "MNeMiC.LLM.LivePreview",
      name: "Stream & Preview",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Live Preview"],
      tooltip: "Stream the reply onto the node as it is written, and allow Cancel to stop a request mid-reply. Turn off for endpoints that don't support streaming.",
      type: "boolean",
      defaultValue: true,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.OllamaLocal",
      name: "Ollama (this PC)",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "Ollama (this PC)"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -10,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.OllamaNetwork",
      name: "Ollama (network)",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "Ollama (network)"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -20,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.LMStudio",
      name: "LM Studio (this PC)",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "LM Studio (this PC)"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -30,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.OpenAICompatible",
      name: "OpenAI-compatible server",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "OpenAI-compatible server"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -40,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.ClaudeCodeSubscription",
      name: "Local Claude Code Subscription",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "Local Claude Code Subscription"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -50,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.CodexSubscription",
      name: "Local Codex Subscription",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "Local Codex Subscription"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -60,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.OpenAI",
      name: "OpenAI (ChatGPT)",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "OpenAI (ChatGPT)"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -70,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.Anthropic",
      name: "Anthropic (Claude)",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "Anthropic (Claude)"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -80,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.Gemini",
      name: "Google (Gemini)",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "Google (Gemini)"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -90,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.Grok",
      name: "xAI (Grok)",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "xAI (Grok)"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -100,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.Groq",
      name: "Groq",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "Groq"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -110,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.OpenRouter",
      name: "OpenRouter",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "OpenRouter"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -120,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.Mistral",
      name: "Mistral",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "Mistral"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -130,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.DeepSeek",
      name: "DeepSeek",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "DeepSeek"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -140,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.Sanctum",
      name: "Sanctum",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "Sanctum"],
      tooltip: "Show this endpoint in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: false,
      sortOrder: -150,
    },
    {
      id: "MNeMiC.LLM.ShowEndpoint.CustomEndpoint",
      name: "Custom Endpoint",
      category: ["⚡MNeMiC Nodes", "LLM Request", "Show Endpoints", "Custom Endpoint"],
      tooltip: "Show the ad-hoc Custom Endpoint entry in the LLM Request node's endpoint dropdown.",
      type: "boolean",
      defaultValue: true,
      sortOrder: -160,
    },
    {
      id: "MNeMiC.GroqCompletion.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq Completion API", "Console Logging"],
      tooltip: "Log Groq Completion API request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqCompletion.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq Completion API", "Request Timeout"],
      tooltip: "How long to wait for the Groq Completion API to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.GroqTranscribe.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Transcribe", "Console Logging"],
      tooltip: "Log Groq ALM API - Transcribe request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqTranscribe.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Transcribe", "Request Timeout"],
      tooltip: "How long to wait for the Groq ALM API - Transcribe to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.GroqTranslate.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Translate", "Console Logging"],
      tooltip: "Log Groq ALM API - Translate request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqTranslate.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Translate", "Request Timeout"],
      tooltip: "How long to wait for the Groq ALM API - Translate to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.PromptPropertyExtractor.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Prompt Property Extractor", "Console Logging"],
      tooltip: "Log Prompt Property Extractor parsing/matching details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.LoadRandomCheckpoint.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Load Random Checkpoint", "Console Logging"],
      tooltip: "Log Load Random Checkpoint pool/matching details to the console.",
      type: "boolean",
      defaultValue: false,
    },
  ],
});
