import { app } from "../../../scripts/app.js";
import { refreshWildcardHighlighters } from "./wildcard_highlight_core.js";

// All wildcard settings share one group, shown first on the MNeMiC page
// (groups are ordered by their highest sortOrder).
const WILDCARD_CATEGORY = ["⚡MNeMiC Nodes", "Wildcard Processing"];

app.registerExtension({
  name: "MNeMiC.Settings",
  settings: [
    {
      id: "MNeMiC.LoRALoading.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "LoRA Loading", "Console Logging"],
      tooltip: "Log LoRA Tag Loader matching and loading details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.LoRALoading.FuzzySearch",
      name: "Fuzzy search",
      category: ["⚡MNeMiC Nodes", "LoRA Loading", "Fuzzy Search"],
      tooltip: "Allow LoRA Tag Loader to fall back to fuzzy (partial/reordered word) filename matching when no exact match is found. Disabled by default so only exact, base, numbered and prefix/contains matches are used.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.WildcardProcessing.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Console Logging"],
      sortOrder: 110,
      tooltip: "Log Wildcard Processor, Wildcard Processor Advanced and Batch Wildcard Sampler matching and processing details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.WildcardProcessing.FuzzySearch",
      name: "Fuzzy search",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Fuzzy Search"],
      sortOrder: 109,
      tooltip: "Allow wildcard matching to fall back to fuzzy (partial/reordered word) filename matching when no exact match is found. Disabled by default so only exact, base, numbered and prefix/contains matches are used.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.LoRALoading.MaxLoggedCandidates",
      name: "Max logged candidates",
      category: ["⚡MNeMiC Nodes", "LoRA Loading", "Max Logged Candidates"],
      tooltip: "How many candidate LoRA files to list in the console log when Console Logging is on. LoRA folders can hold hundreds of matches, so the log only shows the most relevant ones.",
      type: "number",
      attrs: { min: 1, max: 100, step: 1 },
      defaultValue: 15,
    },
    {
      id: "MNeMiC.WildcardProcessing.MaxLoggedCandidates",
      name: "Max logged candidates",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Max Logged Candidates"],
      sortOrder: 108,
      tooltip: "How many candidate wildcard files to list in the console log when Console Logging is on. Wildcard folders can hold hundreds of matches, so the log only shows the most relevant ones.",
      type: "number",
      attrs: { min: 1, max: 100, step: 1 },
      defaultValue: 15,
    },
    {
      id: "MNeMiC.WildcardProcessing.MaxNestedPasses",
      name: "Max nested passes",
      category: ["⚡MNeMiC Nodes", "Wildcard Processing", "Max Nested Passes"],
      sortOrder: 107,
      tooltip: "Maximum number of passes when resolving wildcards nested inside other wildcards. Increase if you have deeply nested wildcard chains that aren't fully resolving.",
      type: "number",
      attrs: { min: 1, max: 50, step: 1 },
      defaultValue: 10,
    },
    {
      id: "MNeMiC.WildcardHighlight.Enabled",
      name: "Enable wildcard highlighting",
      category: [...WILDCARD_CATEGORY, "Enabled"],
      sortOrder: 200,
      tooltip: "Color the parts of wildcard prompts ({a|b} blocks, ${variables}, __file__ wildcards, <tags>) in the text boxes of the Wildcard Processor, Wildcard Processor Advanced, Batch Wildcard Upscale Sampler and Prompt Property Extractor nodes.",
      type: "boolean",
      defaultValue: true,
      onChange: () => refreshWildcardHighlighters(),
    },
    {
      id: "MNeMiC.WildcardHighlight.Palette",
      name: "Highlight color palette",
      category: [...WILDCARD_CATEGORY, "Palette"],
      sortOrder: 199,
      tooltip: "Dark (the default) gives soft tints on ComfyUI's dark theme. Pastel and Light are brighter backgrounds. Vivid suits Text color and Underline. Custom uses the colors from 'Highlight custom colors'.",
      type: "combo",
      options: ["Pastel", "Light", "Vivid", "Dark", "Muted", "Custom"],
      defaultValue: "Dark",
      onChange: () => refreshWildcardHighlighters(),
    },
    {
      id: "MNeMiC.WildcardHighlight.Style",
      name: "Highlight style",
      category: [...WILDCARD_CATEGORY, "Style"],
      sortOrder: 198,
      tooltip: "How the colors are applied: as a background behind the text, as the text color, both, or as an underline.",
      type: "combo",
      options: ["Background", "Text color", "Background + text color", "Underline"],
      defaultValue: "Background",
      onChange: () => refreshWildcardHighlighters(),
    },
    {
      id: "MNeMiC.WildcardHighlight.Coloring",
      name: "Highlight blocks by",
      category: [...WILDCARD_CATEGORY, "Coloring"],
      sortOrder: 197,
      tooltip: "Each block: every {a|b} block gets its own color. Nesting depth: blocks at the same nesting level share a color.\nVariables and __file__ wildcards are always colored by name, so a variable's definition and every use of it share one color.",
      type: "combo",
      options: ["Each block", "Nesting depth"],
      defaultValue: "Each block",
      onChange: () => refreshWildcardHighlighters(),
    },
    {
      id: "MNeMiC.WildcardHighlight.Intensity",
      name: "Highlight background intensity (%)",
      category: [...WILDCARD_CATEGORY, "Intensity"],
      sortOrder: 196,
      tooltip: "Opacity of highlight backgrounds. Nested blocks stack on top of each other, so lower values keep deep nesting readable.",
      type: "slider",
      attrs: { min: 5, max: 100, step: 5 },
      defaultValue: 35,
      onChange: () => refreshWildcardHighlighters(),
    },
    {
      id: "MNeMiC.WildcardHighlight.EmphasizeSyntax",
      name: "Highlight syntax characters more strongly",
      category: [...WILDCARD_CATEGORY, "Emphasize Syntax"],
      sortOrder: 195,
      tooltip: "Give braces, | separators, weights (5::), counts (2$$) and separators a stronger shade of their block's color, so option boundaries are easy to spot.",
      type: "boolean",
      defaultValue: true,
      onChange: () => refreshWildcardHighlighters(),
    },
    {
      id: "MNeMiC.WildcardHighlight.MarkErrors",
      name: "Highlight syntax errors",
      category: [...WILDCARD_CATEGORY, "Mark Errors"],
      sortOrder: 194,
      tooltip: "Underline unclosed { or ${, stray }, unbalanced ${name=!...} definitions, and ${variables} used where they are not defined, with a red wavy line. A variable's value only sees variables defined inside that value.",
      type: "boolean",
      defaultValue: true,
      onChange: () => refreshWildcardHighlighters(),
    },
    {
      id: "MNeMiC.WildcardHighlight.CustomColors",
      name: "Highlight custom colors",
      category: [...WILDCARD_CATEGORY, "Custom Colors"],
      sortOrder: 193,
      tooltip: "Used when the palette is set to Custom. A list of colors separated by commas or spaces, as #rgb, #rrggbb or rgb(r, g, b). Example: #ffb3ba, #ffdfba, #ffffba, #baffc9, #bae1ff",
      type: "text",
      defaultValue: "#ffb3ba, #ffdfba, #ffffba, #baffc9, #bae1ff, #e0bbff",
      onChange: () => refreshWildcardHighlighters(),
    },
    {
      id: "MNeMiC.GroqLLM.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq LLM API", "Console Logging"],
      tooltip: "Log Groq LLM API request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqLLM.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq LLM API", "Request Timeout"],
      tooltip: "How long to wait for the Groq LLM API to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.GroqCompletion.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq Completion API", "Console Logging"],
      tooltip: "Log Groq Completion API request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqCompletion.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq Completion API", "Request Timeout"],
      tooltip: "How long to wait for the Groq Completion API to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.GroqTranscribe.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Transcribe", "Console Logging"],
      tooltip: "Log Groq ALM API - Transcribe request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqTranscribe.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Transcribe", "Request Timeout"],
      tooltip: "How long to wait for the Groq ALM API - Transcribe to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.GroqTranslate.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Translate", "Console Logging"],
      tooltip: "Log Groq ALM API - Translate request/response details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.GroqTranslate.RequestTimeout",
      name: "Request timeout (seconds)",
      category: ["⚡MNeMiC Nodes", "Groq ALM API - Translate", "Request Timeout"],
      tooltip: "How long to wait for the Groq ALM API - Translate to respond before timing out and retrying.",
      type: "number",
      attrs: { min: 5, max: 600, step: 5 },
      defaultValue: 120,
    },
    {
      id: "MNeMiC.PromptPropertyExtractor.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Prompt Property Extractor", "Console Logging"],
      tooltip: "Log Prompt Property Extractor parsing/matching details to the console.",
      type: "boolean",
      defaultValue: false,
    },
    {
      id: "MNeMiC.LoadRandomCheckpoint.ConsoleLogging",
      name: "Console logging",
      category: ["⚡MNeMiC Nodes", "Load Random Checkpoint", "Console Logging"],
      tooltip: "Log Load Random Checkpoint pool/matching details to the console.",
      type: "boolean",
      defaultValue: false,
    },
  ],
});
