import os
import json
import time
from colorama import Fore, Style
from groq import Groq
import requests

from ..utils.api_utils import load_prompt_options, get_prompt_content
from ..utils.env_manager import ensure_env_file, get_api_key
from ..utils.settings_utils import is_groq_translate_console_log_enabled, get_groq_translate_request_timeout

from comfy_api.latest import io

# Lazily-initialised API key and prompt options, shared by every instance of the
# node. V3 nodes execute as classmethods, so this replaces the old __init__.
_CONTEXT = None


def _get_context():
    """Return (api_key, prompt_options), initialising them on first use."""
    global _CONTEXT
    if _CONTEXT is None:
        current_directory = os.path.dirname(os.path.realpath(__file__))
        groq_directory = os.path.join(current_directory, 'groq')

        # Get API key from env file
        ensure_env_file()
        api_key = get_api_key()
        Groq(api_key=api_key)

        # Load prompt options
        prompt_files = [
            os.path.join(groq_directory, 'DefaultPrompts_ALM_Translate.json'),
            os.path.join(groq_directory, 'UserPrompts_ALM_Translate.json')
        ]
        _CONTEXT = (api_key, load_prompt_options(prompt_files))
    return _CONTEXT


class GroqAPIALMTranslate(io.ComfyNode):
    DEFAULT_PROMPT = "Translate the audio file using the style and guidance of [user_input]"

    # Only whisper-large-v3 supports translation
    TRANSLATION_MODELS = [
        "whisper-large-v3",
    ]

    SUPPORTED_AUDIO_FORMATS = ['mp3', 'mp4', 'mpeg', 'mpga', 'm4a', 'wav', 'webm']

    @classmethod
    def define_schema(cls) -> io.Schema:
        try:
            current_directory = os.path.dirname(os.path.realpath(__file__))
            groq_directory = os.path.join(current_directory, 'groq')
            prompt_files = [
                os.path.join(groq_directory, 'DefaultPrompts_ALM_Translate.json'),
                os.path.join(groq_directory, 'UserPrompts_ALM_Translate.json')
            ]
            prompt_options = load_prompt_options(prompt_files)
        except Exception as e:
            print(Fore.RED + f"Failed to load prompt options: {e}" + Style.RESET_ALL)
            prompt_options = {}

        return io.Schema(
            node_id="MNeMiC_GroqAPIALMTranslate",
            display_name="✨🌐 Groq ALM API - Translate [EN only]",
            category="⚡ MNeMiC Nodes",
            description="Uses Groq API to translate audio.",
            inputs=[
                io.Combo.Input("model", options=cls.TRANSLATION_MODELS, tooltip="Select the translation model to use."),
                io.String.Input("file_path", multiline=False, default="", tooltip="Path to the audio file for translation."),
                io.Combo.Input("preset", options=[cls.DEFAULT_PROMPT] + list(prompt_options.keys()), tooltip="Select a preset or custom prompt for guiding the translation."),
                io.String.Input("user_input", multiline=True, default="", tooltip="Optional user input to guide the translation process."),
                io.Combo.Input("response_format", advanced=True, options=["json", "verbose_json", "text", "text_with_timestamps", "text_with_linebreaks"], tooltip="Choose the format in which the translation output will be returned."),
                io.Float.Input("temperature", advanced=True, default=0.0, min=0.0, max=1.0, step=0.1, tooltip="Controls randomness in responses.\n\nA higher temperature makes the model take more risks, leading to more creative or varied answers.\n\nA lower temperature (closer to 0.1) makes the model more focused and predictable."),
                io.Int.Input("max_retries", advanced=True, default=2, min=1, max=10, step=1, tooltip="Maximum number of retries in case of failures."),
            ],
            outputs=[
                io.String.Output(display_name="translation_result", tooltip="The API response. This is the translation generated by the model"),
                io.Boolean.Output(display_name="success", tooltip="Whether the request was successful"),
                io.String.Output(display_name="status_code", tooltip="The status code of the request"),
            ],
        )

    @classmethod
    def execute(cls, model, file_path, preset, user_input, response_format, temperature, max_retries) -> io.NodeOutput:
        api_key, prompt_options_loaded = _get_context()
        # Validate file path
        if not os.path.isfile(file_path):
            print(Fore.RED + f"Error: File not found at path {file_path}" + Style.RESET_ALL)
            return io.NodeOutput("File not found.", False, "400 Bad Request")

        # Validate file extension
        file_extension = file_path.split('.')[-1].lower()
        if file_extension not in cls.SUPPORTED_AUDIO_FORMATS:
            print(Fore.RED + f"Error: Unsupported audio format '{file_extension}'. Supported formats are: {', '.join(cls.SUPPORTED_AUDIO_FORMATS)}" + Style.RESET_ALL)
            return io.NodeOutput(f"Unsupported audio format '{file_extension}'.", False, "400 Bad Request")

        # Load the audio file
        try:
            with open(file_path, 'rb') as audio_file:
                audio_data = audio_file.read()
        except Exception as e:
            print(Fore.RED + f"Error reading audio file: {str(e)}" + Style.RESET_ALL)
            return io.NodeOutput("Error reading audio file.", False, "400 Bad Request")

        # Prepare the prompt
        if preset == cls.DEFAULT_PROMPT:
            prompt = cls.DEFAULT_PROMPT.replace('[user_input]', user_input.strip()) if user_input else None
        else:
            prompt_template = get_prompt_content(prompt_options_loaded, preset)
            prompt = prompt_template.replace('[user_input]', user_input.strip())

        # Limit the prompt to 224 tokens
        # if prompt:
        #     prompt = prompt[:1000]

        # Adjust api_response_format based on response_format
        if response_format in ['json', 'verbose_json', 'text']:
            api_response_format = response_format
        elif response_format in ['text_with_timestamps', 'text_with_linebreaks']:
            api_response_format = 'verbose_json'
        else:
            return io.NodeOutput("Unknown response format.", False, "400 Bad Request")

        url = 'https://api.groq.com/openai/v1/audio/translations'
        headers = {'Authorization': f'Bearer {api_key}'}
        files = {'file': (os.path.basename(file_path), audio_data)}
        data = {
            'model': model,
            'response_format': api_response_format,
            'temperature': str(temperature),
        }
        if prompt:
            data['prompt'] = prompt

        console_log = is_groq_translate_console_log_enabled()
        if console_log:
            print(f"Sending request to {url} with data: {data} and headers: {{'Authorization': 'Bearer ***'}}")

        # Send the request
        request_timeout = get_groq_translate_request_timeout()
        for attempt in range(max_retries):
            try:
                response = requests.post(url, headers=headers, data=data, files=files, timeout=request_timeout)
                if console_log:
                    print(f"Response status: {response.status_code}")
                if response.status_code == 200:
                    if api_response_format == "text":
                        if response_format == "text":
                            # Return plain text as is
                            return io.NodeOutput(response.text, True, "200 OK")
                    elif api_response_format in ["json", "verbose_json"]:
                        try:
                            response_json = json.loads(response.text)
                        except Exception as e:
                            print(Fore.RED + f"Error parsing JSON response: {str(e)}" + Style.RESET_ALL)
                            return io.NodeOutput("Error parsing JSON response.", False, "200 OK but failed to parse JSON")
                        if response_format == "json":
                            # Return JSON as formatted string
                            return io.NodeOutput(json.dumps(response_json, indent=4), True, "200 OK")
                        elif response_format == "verbose_json":
                            # Return verbose JSON as formatted string
                            return io.NodeOutput(json.dumps(response_json, indent=4), True, "200 OK")
                        elif response_format == "text_with_timestamps":
                            # Process segments to produce line-based timestamps
                            segments = response_json.get('segments', [])
                            translation_text = ""
                            for segment in segments:
                                start_time = segment.get('start', 0)
                                # Convert start_time to minutes:seconds.milliseconds
                                minutes = int(start_time // 60)
                                seconds = int(start_time % 60)
                                milliseconds = int((start_time - int(start_time)) * 1000)
                                timestamp = f"[{minutes:02d}:{seconds:02d}.{milliseconds:03d}]"
                                text = segment.get('text', '').strip()
                                translation_text += f"{timestamp}{text}\n"
                            return io.NodeOutput(translation_text.strip(), True, "200 OK")
                        elif response_format == "text_with_linebreaks":
                            # Extract text from each segment and concatenate with line breaks
                            segments = response_json.get('segments', [])
                            translation_text = ""
                            for segment in segments:
                                text = segment.get('text', '').strip()
                                translation_text += f"{text}\n"
                            return io.NodeOutput(translation_text.strip(), True, "200 OK")
                    else:
                        return io.NodeOutput("Unknown api_response_format.", False, "400 Bad Request")
                else:
                    print(Fore.RED + f"Error: {response.status_code} {response.reason}" + Style.RESET_ALL)
                    return io.NodeOutput(response.text, False, f"{response.status_code} {response.reason}")
            except Exception as e:
                print(Fore.RED + f"Request failed: {str(e)}" + Style.RESET_ALL)
                time.sleep(2)
        return io.NodeOutput("Failed after all retries.", False, "Failed after all retries")
