import os
import json
import random
import numpy as np
import torch
from colorama import Fore, Style
from groq import Groq

from ..utils.api_utils import make_api_request, load_prompt_options, get_prompt_content
from ..utils.env_manager import ensure_env_file, get_api_key
from ..utils.image_utils import encode_image, tensor_to_pil

from comfy_api.latest import io

# Lazily-initialised API key and prompt options, shared by every instance of the
# node. V3 nodes execute as classmethods, so this replaces the old __init__.
_CONTEXT = None


def _get_context():
    """Return (api_key, prompt_options), initialising them on first use."""
    global _CONTEXT
    if _CONTEXT is None:
        current_directory = os.path.dirname(os.path.realpath(__file__))
        groq_directory = os.path.join(current_directory, 'groq')

        # Get API key from env file
        ensure_env_file()
        api_key = get_api_key()
        Groq(api_key=api_key)

        # Load prompt options
        prompt_files = [
            os.path.join(groq_directory, 'DefaultPrompts_VLM.json'),
            os.path.join(groq_directory, 'UserPrompts_VLM.json')
        ]
        _CONTEXT = (api_key, load_prompt_options(prompt_files))
    return _CONTEXT


class GroqAPIVLM(io.ComfyNode):
    DEFAULT_PROMPT = "Use [system_message] and [user_input]"
    
    # Deprecation List - https://console.groq.com/docs/deprecations

    VLM_MODELS = [
        "meta-llama/llama-4-maverick-17b-128e-instruct",
        "meta-llama/llama-4-scout-17b-16e-instruct",
    ]
    
    @classmethod
    def define_schema(cls) -> io.Schema:
        try:
            current_directory = os.path.dirname(os.path.realpath(__file__))
            groq_directory = os.path.join(current_directory, 'groq')
            prompt_files = [
                os.path.join(groq_directory, 'DefaultPrompts_VLM.json'),
                os.path.join(groq_directory, 'UserPrompts_VLM.json')
            ]
            prompt_options = load_prompt_options(prompt_files)
        except Exception as e:
            print(Fore.RED + f"Failed to load prompt options: {e}" + Style.RESET_ALL)
            prompt_options = {}
    
        return io.Schema(
            node_id="MNeMiC_GroqAPIVLM",
            display_name="✨📷 Groq VLM API",
            category="⚡ MNeMiC Nodes",
            description="Uses Groq API for image processing.",
            inputs=[
                io.Combo.Input("model", options=cls.VLM_MODELS, tooltip="Select the Vision-Language Model (VLM) to use."),
                io.Combo.Input("preset", options=[cls.DEFAULT_PROMPT] + list(prompt_options.keys()), tooltip="Select a preset prompt or use a custom prompt for the model."),
                io.String.Input("system_message", multiline=True, default="", tooltip="Optional system message to guide model behavior."),
                io.String.Input("user_input", multiline=True, default="", tooltip="User input or prompt for the model to generate a response."),
                io.Image.Input("image", tooltip="Upload an image for processing by the VLM model."),
                io.Float.Input("temperature", default=0.85, min=0.1, max=2.0, step=0.05, tooltip="Controls randomness in responses.\n\nA higher temperature makes the model take more risks, leading to more creative or varied answers.\n\nA lower temperature (closer to 0.1) makes the model more focused and predictable."),
                io.Int.Input("max_tokens", advanced=True, default=1024, min=1, max=131072, step=1, tooltip="Maximum number of tokens to generate in the output."),
                io.Float.Input("top_p", advanced=True, default=1.0, min=0.1, max=1.0, step=0.01, tooltip="Limits the pool of words the model can choose from based on their combined probability.\n\nSet it closer to 1 to allow more variety in output. Lowering this (e.g., 0.9) will restrict the output to the most likely words, making responses more focused."),
                io.Int.Input("seed", advanced=True, default=42, min=0, max=4294967295, tooltip="Seed for random number generation, ensuring reproducibility."),
                io.Int.Input("max_retries", advanced=True, default=2, min=1, max=10, step=1, tooltip="Maximum number of retries in case of failures."),
                io.String.Input("stop", advanced=True, default="", tooltip="Stop generation when the specified sequence is encountered."),
                io.Boolean.Input("json_mode", advanced=True, default=False, tooltip="Enable JSON mode for structured output.\n\nIMPORTANT: Requires you to use the word 'JSON' in the prompt."),
            ],
            outputs=[
                io.String.Output(display_name="api_response", tooltip="The API response. This is the description of your input image generated by the model"),
                io.Boolean.Output(display_name="success", tooltip="Whether the request was successful"),
                io.String.Output(display_name="status_code", tooltip="The status code of the request"),
            ],
        )

    @classmethod
    def execute(cls, model, image, temperature, max_tokens, top_p, seed, max_retries, stop, json_mode, preset="", system_message="", user_input="") -> io.NodeOutput:
        api_key, prompt_options_loaded = _get_context()
        # Set the seed for reproducibility
        torch.manual_seed(seed)
        np.random.seed(seed)
        random.seed(seed)
    
        if preset == cls.DEFAULT_PROMPT:
            system_message = system_message
        else:
            system_message = get_prompt_content(prompt_options_loaded, preset)
    
        url = 'https://api.groq.com/openai/v1/chat/completions'
        headers = {'Authorization': f'Bearer {api_key}'}
        
        if image is not None and isinstance(image, torch.Tensor):
            # Process the image
            image_pil = tensor_to_pil(image)
            base64_image = encode_image(image_pil)
            if base64_image:
                combined_message = f"{system_message}\n{user_input}"
                # Send one single message containing both text and image
                image_content = {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": combined_message},
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}
                        }
                    ]
                }
                messages = [image_content]
            else:
                print(Fore.RED + "Failed to encode image." + Style.RESET_ALL)
                messages = []
        else:
            print(Fore.RED + "Image is required for VLM models." + Style.RESET_ALL)
            return io.NodeOutput("Image is required for VLM models.", False, "400 Bad Request")
       
        data = {
            'model': model,
            'messages': messages,
            'temperature': temperature,
            'max_tokens': max_tokens,
            'top_p': top_p,
            'seed': seed
        }
        
        if stop:  # Only add stop if it's not empty
            data['stop'] = stop
        
        #print(f"Sending request to {url} with data: {json.dumps(data, indent=4)} and headers: {headers}")
        
        assistant_message, success, status_code = make_api_request(data, headers, url, max_retries)
        return io.NodeOutput(assistant_message, success, status_code)
