import os
import time
import json
import requests
import random
import numpy as np
import torch
from groq import Groq
import base64
from PIL import Image

from ..utils.api_utils import load_prompt_options, get_prompt_content
from ..utils.env_manager import ensure_env_file, get_api_key
from ..utils.settings_utils import is_groq_completion_console_log_enabled, get_groq_completion_request_timeout

from comfy_api.latest import io

# Lazily-initialised API key, shared by every instance of the node. V3 nodes
# execute as classmethods, so this replaces the old __init__.
_API_KEY = None


def _get_api_key():
    global _API_KEY
    if _API_KEY is None:
        ensure_env_file()
        _API_KEY = get_api_key()
        Groq(api_key=_API_KEY)
    return _API_KEY


class GroqAPICompletion(io.ComfyNode):
    DEFAULT_PROMPT = "Use [system_message] and [user_input]"

    @classmethod
    def define_schema(cls) -> io.Schema:
        try:
            prompt_options = cls.load_prompt_options()
        except Exception as e:
            print(f"Failed to load prompt options: {e}")
            prompt_options = {}

        return io.Schema(
            node_id="MNeMiC_GroqAPICompletion",
            display_name="✨💬 Groq Completion API",
            category="⚡ MNeMiC Nodes",
            inputs=[
                io.Combo.Input("model", options=[
                    "llama-3.1-8b-instant",
                    "llama-3.1-70b-versatile",
                    "llama3-8b-8192",
                    "llama3-70b-8192",
                    "llama-guard-3-8b",
                    "llama3-groq-8b-8192-tool-use-preview",
                    "llama3-groq-70b-8192-tool-use-preview",
                    "mixtral-8x7b-32768",
                    "gemma-7b-it",
                    "gemma2-9b-it",
                    "whisper-large-v3",
                    "distil-whisper-large-v3-en",
                    "llava-v1.5-7b-4096-preview",
                ], tooltip="Model to send the request to."),
                io.Combo.Input("preset", options=[cls.DEFAULT_PROMPT] + list(prompt_options.keys()), tooltip="Preset system prompt, or the default to use the system_message field below."),
                io.String.Input("system_message", multiline=True, default="", tooltip="Instructions that set the model's role and behaviour. Used only when preset is the default."),
                io.String.Input("user_input", multiline=True, default="", tooltip="The request sent to the model."),
                io.Float.Input("temperature", default=0.85, min=0.1, max=2.0, step=0.05, tooltip="Randomness of the reply. Low values are focused and repeatable, high values are more creative."),
                io.Int.Input("max_tokens", default=1024, min=1, max=131072, step=1, tooltip="Maximum length of the reply, in tokens."),
                io.Float.Input("top_p", default=1.0, min=0.1, max=1.0, step=0.01, tooltip="Nucleus sampling cutoff. 1.0 considers every candidate word; lower values keep only the most likely ones."),
                io.Int.Input("seed", default=42, min=0, max=4294967295, tooltip="Seed sent to the API for repeatable replies."),
                io.Int.Input("max_retries", default=2, min=1, max=10, step=1, tooltip="How many times to retry a failed request before giving up."),
                io.String.Input("stop", default="", tooltip="Stop generating when this sequence appears. Leave empty for no stop sequence."),
                io.Boolean.Input("json_mode", default=False, tooltip="Force the reply to be valid JSON. The word JSON must also appear in the prompt."),
                io.Image.Input("image", optional=True, tooltip="Image to describe. Only used by the llava model."),
            ],
            outputs=[
                io.String.Output(display_name="api_response", tooltip="The text generated by the model."),
                io.Boolean.Output(display_name="success", tooltip="True when the request completed, False on any error."),
                io.String.Output(display_name="status_code", tooltip="HTTP status of the request, e.g. \"200 OK\"."),
            ],
        )

    @classmethod
    def execute(cls, model, preset, system_message, user_input, temperature, max_tokens, top_p, seed, max_retries, stop, json_mode, image=None) -> io.NodeOutput:
        # Set the seed for reproducibility
        torch.manual_seed(seed)
        np.random.seed(seed)
        random.seed(seed)

        system_message = system_message if preset == cls.DEFAULT_PROMPT else cls.get_prompt_content(preset)

        url = 'https://api.groq.com/openai/v1/chat/completions'
        headers = {'Authorization': f'Bearer {_get_api_key()}'}
        
        messages = [
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_input}
        ]
        
        # If the selected model is llava-v1.5-7b-4096-preview, include the image
        if model == "llava-v1.5-7b-4096-preview":
            if image is not None and isinstance(image, torch.Tensor):
                # Process the image only if it is provided
                image_pil = cls.tensor_to_pil(image)
                base64_image = cls.encode_image(image_pil)

                if base64_image:
                    combined_message = f"{system_message}\n{user_input}"

                    # Send one single message containing both text and image
                    image_content = {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": combined_message},
                            {
                                "type": "image_url",
                                "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}
                            }
                        ]
                    }
                    messages = [image_content]
   
        data = {
            'model': model,
            'messages': messages,
            'temperature': temperature,
            'max_tokens': max_tokens,
            'top_p': top_p,
            'seed': seed
        }
        
        if stop:  # Only add stop if it's not empty
            data['stop'] = stop
        
        console_log = is_groq_completion_console_log_enabled()
        if console_log:
            print(f"Sending request to {url} with data: {json.dumps(data, indent=4)} and headers: {{'Authorization': 'Bearer ***'}}")

        request_timeout = get_groq_completion_request_timeout()
        for attempt in range(max_retries):
            response = requests.post(url, headers=headers, json=data, timeout=request_timeout)
            if console_log:
                print(f"Response status: {response.status_code}, Response body: {response.text}")
            if response.status_code == 200:
                try:
                    response_json = json.loads(response.text)
                    if 'choices' in response_json and response_json['choices']:
                        assistant_message = response_json['choices'][0]['message']['content']
                        if console_log:
                            print(f"Extracted message: {assistant_message}")
                        return io.NodeOutput(assistant_message, True, "200 OK")
                    else:
                        return io.NodeOutput("No valid response content found.", False, "200 OK but no content")
                except Exception as e:
                    print(f"Error parsing response: {str(e)}")
                    return io.NodeOutput("Error parsing JSON response.", False, "200 OK but failed to parse JSON")
            else:
                return io.NodeOutput("ERROR", False, f"{response.status_code} {response.reason}")

            time.sleep(2)
        
        return io.NodeOutput("Failed after all retries.", False, "Failed after all retries")

    @classmethod
    def load_prompt_options(cls):
        current_directory = os.path.dirname(os.path.realpath(__file__))
        groq_directory = os.path.join(current_directory, 'groq')
        prompt_options = {}
        json_files = ['DefaultPrompts.json', 'UserPrompts.json']
        for json_file in json_files:
            json_path = os.path.join(groq_directory, json_file)
            try:
                with open(json_path, 'r') as file:
                    prompts = json.load(file)
                    prompt_options.update({prompt['name']: prompt['content'] for prompt in prompts})
            except Exception as e:
                print(f"Failed to load prompts from {json_path}: {str(e)}")
        return prompt_options

    @classmethod
    def get_prompt_content(cls, prompt_name):
        return cls.load_prompt_options().get(prompt_name, "No content found for selected prompt")

    # Function to encode image in base64
    @classmethod
    def encode_image(cls, image_path):
        try:
            with open(image_path, "rb") as image_file:
                return base64.b64encode(image_file.read()).decode('utf-8')
        except Exception as e:
            print(f"Error encoding image: {e}")
            return None

    @classmethod
    def tensor_to_pil(cls, image_tensor):
        # Remove batch dimension if it exists (tensor shape [1, H, W, C])
        if image_tensor.ndim == 4 and image_tensor.shape[0] == 1:
            image_tensor = image_tensor.squeeze(0)  # Remove the batch dimension

        # Ensure the tensor is in the form [H, W, C] (height, width, channels)
        if image_tensor.ndim == 3 and image_tensor.shape[2] == 3:  # Expecting RGB image with 3 channels
            image_array = image_tensor.cpu().numpy()
            image_array = (image_array * 255).astype(np.uint8)  # Convert from [0, 1] to [0, 255]
            return Image.fromarray(image_array)
        else:
            raise TypeError(f"Unsupported image tensor shape: {image_tensor.shape}")

    # Save the image locally for debugging
    @classmethod
    def save_image(cls, image_pil, filename="vlm_image_temp.png"):
        try:
            current_directory = os.path.dirname(os.path.realpath(__file__))
            groq_directory = os.path.join(current_directory, 'groq')
            image_path = os.path.join(groq_directory, filename)
            image_pil.save(image_path)
            print(f"Image saved at {image_path}")
            return image_path
        except Exception as e:
            print(f"Error saving image: {e}")
            return None